version: '3.8'

services:
  mongodb:
    build: .
    image: challenge-db-image
    container_name: challenge-db
    ports:
      - "27028:27028"
    volumes:
      - ./data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
